### ISSUE TITLE
kl-divergence value undefined

### ISSUE THREAD

**Issue by mctigger** [mazpie/mastering-urlb#1]
https://github.com/mazpie/mastering-urlb/blob/99fad8525eef349a68552e4b52e55e211077d5ee/agent/dreamer_utils.py#L320-L341

`value` seems to be undefined for balance != 0.5 or am I missing something?

**Comment by mazpie** [comment]
Hi @mctigger ,

Please check line 332: `value` is defined same as `value_lhs`, when `balance != 0.5`

Hope this is helpful!

**Comment by mctigger** [comment]
Ah, thank you very much :) I overlooked it!
