### ISSUE TITLE
Question about action and state mismatch

### ISSUE THREAD

**Issue by dwyzzy** [mazpie/mastering-urlb#2]
Thanks for the repository.

I'm wondering whether there is a mismatch between actions and states.

Here is the [code](https://github.com/mazpie/mastering-urlb/blob/99fad8525eef349a68552e4b52e55e211077d5ee/agent/dreamer.py#L251):
```
  def loss(self, data, state=None):
    data = self.preprocess(data)
    embed = self.encoder(data)
    post, prior = self.rssm.observe(
        embed, data['action'], data['is_first'], state)
```
In my opinion, $z_t$ should be calculated using $o_t$ and $a_{t-1}$. Will this code result in $z_t$ being calculated using $o_t$ and $a_t$?

**Comment by dwyzzy** [comment]
Oh, I find I have made some mistakes. Sorry.

**Comment by mazpie** [comment]
No problem, I hope you find the code useful!
